
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class salesdetaile
{

    public int TDetailNo { get; set; }

    public int InvoiceNo { get; set; }

    public int ProductNo { get; set; }

    public string TDDesc { get; set; }

    public Nullable<int> Unitid { get; set; }

    public decimal ItemPrice { get; set; }

    public double Quantity { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Discount { get; set; }

    public Nullable<decimal> Totafterdiscount { get; set; }

    public Nullable<decimal> Total { get; set; }

}

}
